/*db.partidas.drop()
db.partidas.insertMany([
    {   
        _id: 1,
        Jornada: "Cuartos de Final",
        Equipo1: "Vodafone Giants",
        Equipo2: "Movistar Riders",
        Resultado: "3:1",
        Fecha: new Date("2021-03-15"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 2,
        Jornada: "Cuartos de Final",
        Equipo1: "Cream Real Betis",
        Equipo2: "Team Queso",
        Resultado: "3:1",
        Fecha: new Date("2021-03-16"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 3,
        Jornada: "Semifinales",
        Equipo1: "UCAM Esports Club",
        Equipo2: "Vodafone Giants",
        Resultado: "3:1",
        Fecha: new Date("2021-03-19"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 4,
        Jornada: "Semifinales",
        Equipo1: "G2 ARCTIC",
        Equipo2: "Cream Real Betis",
        Resultado: "0:3",
        Fecha: new Date("2021-03-20"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 5,
        Jornada: "Final",
        Equipo1: "UCAM Esports Club",
        Equipo2: "Cream Real Betis",
        Resultado: "3:0",
        Fecha: new Date("2021-03-25"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 6,
        Jornada: "1",
        Equipo1: "Cream Real Betis",
        Equipo2: "MAD Lions Madrid",
        Resultado: "0:1",
        Fecha: new Date("2021-01-18"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 7,
        Jornada: "1",
        Equipo1: "BCN Squad",
        Equipo2: "UCAM Esports CLub",
        Resultado: "0:1",
        Fecha: new Date("2021-01-18"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 8,
        Jornada: "1",
        Equipo1: "eMonkeyz Club",
        Equipo2: "S2V Esports",
        Resultado: "0:1",
        Fecha: new Date("2021-01-18"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 9,
        Jornada: "1",
        Equipo1: "Team Queso",
        Equipo2: "Vodafone Giants",
        Resultado: "0:1",
        Fecha: new Date("2021-01-18"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 10,
        Jornada: "1",
        Equipo1: "Movistar Riders",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-01-18"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 11,
        Jornada: "2",
        Equipo1: "S2V Esports",
        Equipo2: "UCAM Esports CLub",
        Resultado: "1:0",
        Fecha: new Date("2021-01-20"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 12,
        Jornada: "2",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "BCN Squad",
        Resultado: "0:1",
        Fecha: new Date("2021-01-20"),
        Ganador: "BCN Squad",
    },
    {   
        _id: 13,
        Jornada: "2",
        Equipo1: "G2 Arctic",
        Equipo2: "eMonkeyz CLub",
        Resultado: "1:0",
        Fecha: new Date("2021-01-20"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 14,
        Jornada: "2",
        Equipo1: "Vodafone Giants",
        Equipo2: "Cream Real Betis",
        Resultado: "0:1",
        Fecha: new Date("2021-01-20"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 15,
        Jornada: "2",
        Equipo1: "Team Queso",
        Equipo2: "Movistar Riders",
        Resultado: "0:1",
        Fecha: new Date("2021-01-20"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 16,
        Jornada: "3",
        Equipo1: "BCN Squad",
        Equipo2: "S2V Esports",
        Resultado: "0:1",
        Fecha: new Date("2021-01-21"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 17,
        Jornada: "3",
        Equipo1: "eMonkeyz Club",
        Equipo2: "Team Queso",
        Resultado: "0:1",
        Fecha: new Date("2021-01-21"),
        Ganador: "Team Queso",
    },
    {   
        _id: 18,
        Jornada: "3",
        Equipo1: "UCAM Esports Club",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-01-21"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 19,
        Jornada: "3",
        Equipo1: "Cream Real Betis",
        Equipo2: "Movistar Riders",
        Resultado: "0:1",
        Fecha: new Date("2021-01-21"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 20,
        Jornada: "3",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "Vodafone Giants",
        Resultado: "1:0",
        Fecha: new Date("2021-01-21"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 21,
        Jornada: "4",
        Equipo1: "Vodafone Giants",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-01-25"),
        Ganador: "BCN Squad",
    },
    {   
        _id: 22,
        Jornada: "4",
        Equipo1: "Cream Real Betis",
        Equipo2: "eMonkeyz Club",
        Resultado: "0:1",
        Fecha: new Date("2021-01-25"),
        Ganador: "eMonkeyz Club",
    },
    {   
        _id: 23,
        Jornada: "4",
        Equipo1: "S2V Esports",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-01-25"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 24,
        Jornada: "4",
        Equipo1: "Movistar Riders",
        Equipo2: "MAD Lions Madrid",
        Resultado: "0:1",
        Fecha: new Date("2021-01-25"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 25,
        Jornada: "5",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "eMonkeyz Club",
        Resultado: "1:0",
        Fecha: new Date("2021-01-28"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 26,
        Jornada: "5",
        Equipo1: "UCAM Esports Club",
        Equipo2: "Cream Real Betis",
        Resultado: "0:1",
        Fecha: new Date("2021-01-28"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 27,
        Jornada: "5",
        Equipo1: "G2 Arctic",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-01-28"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 28,
        Jornada: "5",
        Equipo1: "S2V Esports",
        Equipo2: "Team Queso",
        Resultado: "1:0",
        Fecha: new Date("2021-01-28"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 29,
        Jornada: "5",
        Equipo1: "Vodafone Giants",
        Equipo2: "Movistar Riders",
        Resultado: "1:0",
        Fecha: new Date("2021-01-28"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 30,
        Jornada: "6",
        Equipo1: "BCN Squad",
        Equipo2: "Movistar Riders",
        Resultado: "1:0",
        Fecha: new Date("2021-02-1"),
        Ganador: "BCN Squad",
    },
    {   
        _id: 31,
        Jornada: "6",
        Equipo1: "S2V Esports",
        Equipo2: "Cream Real Betis",
        Resultado: "0:1",
        Fecha: new Date("2021-02-1"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 32,
        Jornada: "6",
        Equipo1: "eMonkeyz Club",
        Equipo2: "Vodafone Giants",
        Resultado: "1:0",
        Fecha: new Date("2021-02-1"),
        Ganador: "eMonkeyz CLub",
    },
    {   
        _id: 33,
        Jornada: "6",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "UCAM Esports Club",
        Resultado: "0:1",
        Fecha: new Date("2021-02-1"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 34,
        Jornada: "6",
        Equipo1: "G2 Arctic",
        Equipo2: "Team Queso",
        Resultado: "1:0",
        Fecha: new Date("2021-02-1"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 35,
        Jornada: "7",
        Equipo1: "Movistar Riders",
        Equipo2: "eMonkeyz Club",
        Resultado: "1:0",
        Fecha: new Date("2021-02-4"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 36,
        Jornada: "7",
        Equipo1: "Team Queso",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-02-4"),
        Ganador: "Team Queso",
    },
    {   
        _id: 37,
        Jornada: "7",
        Equipo1: "Crean Real Betis",
        Equipo2: "G2 Arctic",
        Resultado: "1:0",
        Fecha: new Date("2021-02-4"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 38,
        Jornada: "7",
        Equipo1: "UCAM Esports Club",
        Equipo2: "Vodafone Giants",
        Resultado: "0:1",
        Fecha: new Date("2021-02-4"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 39,
        Jornada: "7",
        Equipo1: "S2V Esports",
        Equipo2: "MAD Lions Madrid",
        Resultado: "1:0",
        Fecha: new Date("2021-02-4"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 40,
        Jornada: "8",
        Equipo1: "BCN Squad",
        Equipo2: "eMonkeyz Club",
        Resultado: "1:0",
        Fecha: new Date("2021-02-8"),
        Ganador: "BCN Squad",
    },
    {   
        _id: 41,
        Jornada: "8",
        Equipo1: "Team Queso",
        Equipo2: "Cream Real Betis",
        Resultado: "0:1",
        Fecha: new Date("2021-02-8"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 42,
        Jornada: "8",
        Equipo1: "UCAM Esports Club",
        Equipo2: "Movistar Riders",
        Resultado: "1:0",
        Fecha: new Date("2021-02-8"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 43,
        Jornada: "8",
        Equipo1: "G2 Arctic",
        Equipo2: "MAD Lions Madrid",
        Resultado: "0:1",
        Fecha: new Date("2021-02-8"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 44,
        Jornada: "8",
        Equipo1: "Vodafone Giants",
        Equipo2: "S2V Esports",
        Resultado: "1:0",
        Fecha: new Date("2021-02-8"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 45,
        Jornada: "9",
        Equipo1: "Cream Real Betis",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-02-10"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 46,
        Jornada: "9",
        Equipo1: "eMonkeyz Club",
        Equipo2: "UCAM Esports Club",
        Resultado: "1:0",
        Fecha: new Date("2021-02-10"),
        Ganador: "eMonkeyz Club",
    },
    {   
        _id: 47,
        Jornada: "9",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "Team Queso",
        Resultado: "0:1",
        Fecha: new Date("2021-02-10"),
        Ganador: "Team Queso",
    },
    {   
        _id: 48,
        Jornada: "9",
        Equipo1: "Movistar Riders",
        Equipo2: "S2V Esports",
        Resultado: "1:0",
        Fecha: new Date("2021-02-10"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 49,
        Jornada: "9",
        Equipo1: "G2 Arctic",
        Equipo2: "Vodafone Giants",
        Resultado: "0:1",
        Fecha: new Date("2021-02-10"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 50,
        Jornada: "10",
        Equipo1: "S2V Esports",
        Equipo2: "eMonkeyz Club",
        Resultado: "0:1",
        Fecha: new Date("2021-02-11"),
        Ganador: "eMonkeyz Club",
    },
    {   
        _id: 51,
        Jornada: "10",
        Equipo1: "UCAM Esports Club",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-02-11"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 52,
        Jornada: "10",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "Cream Real Betis",
        Resultado: "0:1",
        Fecha: new Date("2021-02-11"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 53,
        Jornada: "10",
        Equipo1: "Vodafone Giants",
        Equipo2: "Team Queso",
        Resultado: "0:1",
        Fecha: new Date("2021-02-11"),
        Ganador: "Team Queso",
    },
    {   
        _id: 54,
        Jornada: "10",
        Equipo1: "G2 Arctic",
        Equipo2: "Movistar Riders",
        Resultado: "0:1",
        Fecha: new Date("2021-02-11"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 55,
        Jornada: "11",
        Equipo1: "Movistar Riders",
        Equipo2: "Team Queso",
        Resultado: "1:0",
        Fecha: new Date("2021-02-15"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 56,
        Jornada: "11",
        Equipo1: "eMonkeyz Club",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-02-15"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 57,
        Jornada: "11",
        Equipo1: "BCN Squad",
        Equipo2: "MAD Lions Madrid",
        Resultado: "0:1",
        Fecha: new Date("2021-02-15"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 58,
        Jornada: "11",
        Equipo1: "UCAM Esports Club",
        Equipo2: "S2V Esports",
        Resultado: "1:0",
        Fecha: new Date("2021-02-15"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 59,
        Jornada: "11",
        Equipo1: "Cream Real Betis",
        Equipo2: "Vodafone Giants",
        Resultado: "1:0",
        Fecha: new Date("2021-02-15"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 60,
        Jornada: "12",
        Equipo1: "S2V Esports",
        Equipo2: "BCN Squad",
        Resultado: "0:1",
        Fecha: new Date("2021-02-18"),
        Ganador: "BCN Squad",
    },
    {   
        _id: 61,
        Jornada: "12",
        Equipo1: "G2 Arctic",
        Equipo2: "UCAM Esports Club",
        Resultado: "0:1",
        Fecha: new Date("2021-02-18"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 62,
        Jornada: "12",
        Equipo1: "Movistar Riders",
        Equipo2: "Cream Real Betis",
        Resultado: "1:0",
        Fecha: new Date("2021-02-18"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 63,
        Jornada: "12",
        Equipo1: "Team Queso",
        Equipo2: "eMonkeyz Club",
        Resultado: "1:0",
        Fecha: new Date("2021-02-18"),
        Ganador: "Team Queso",
    },
    {   
        _id: 64,
        Jornada: "12",
        Equipo1: "Vodafone Giants",
        Equipo2: "MAD Lions Madrid",
        Resultado: "1:0",
        Fecha: new Date("2021-02-18"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 65,
        Jornada: "13",
        Equipo1: "UCAM Esports Club",
        Equipo2: "Team Queso",
        Resultado: "0:1",
        Fecha: new Date("2021-02-22"),
        Ganador: "Team Queso",
    },
    {   
        _id: 66,
        Jornada: "13",
        Equipo1: "BCN Squad",
        Equipo2: "Vodafone Giants",
        Resultado: "1:0",
        Fecha: new Date("2021-02-22"),
        Ganador: "BCN Squad",
    },
    {   
        _id: 67,
        Jornada: "13",
        Equipo1: "G2 Arctic",
        Equipo2: "S2V Esports",
        Resultado: "0:1",
        Fecha: new Date("2021-02-22"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 68,
        Jornada: "13",
        Equipo1: "eMonkeyz Club",
        Equipo2: "Cream Real Betis",
        Resultado: "1:0",
        Fecha: new Date("2021-02-22"),
        Ganador: "eMonkeyz Club",
    },
    {   
        _id: 69,
        Jornada: "13",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "Movistar Riders",
        Resultado: "0:1",
        Fecha: new Date("2021-02-22"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 70,
        Jornada: "14",
        Equipo1: "eMonkeyz CLub",
        Equipo2: "MAD Lions Madrid",
        Resultado: "0:1",
        Fecha: new Date("2021-02-25"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 71,
        Jornada: "14",
        Equipo1: "Team Queso",
        Equipo2: "S2V Esports",
        Resultado: "1:0",
        Fecha: new Date("2021-02-25"),
        Ganador: "Team Queso",
    },
    {   
        _id: 72,
        Jornada: "14",
        Equipo1: "BCN Squad",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-02-25"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 73,
        Jornada: "14",
        Equipo1: "Cream Real Betis",
        Equipo2: "UCAM Espports Club",
        Resultado: "0:1",
        Fecha: new Date("2021-02-25"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 74,
        Jornada: "14",
        Equipo1: "Movistar Riders",
        Equipo2: "Vodafone Giants",
        Resultado: "0:1",
        Fecha: new Date("2021-02-25"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 75,
        Jornada: "15",
        Equipo1: "Movistar Riders",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-03-1"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 76,
        Jornada: "15",
        Equipo1: "UCAM Esports Club",
        Equipo2: "MAD Lions Madrid",
        Resultado: "1:0",
        Fecha: new Date("2021-03-1"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 77,
        Jornada: "15",
        Equipo1: "Cream Real Betis",
        Equipo2: "S2V Esports",
        Resultado: "1:0",
        Fecha: new Date("2021-03-1"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 78,
        Jornada: "15",
        Equipo1: "Vodafone Giants",
        Equipo2: "eMonkeyz Club",
        Resultado: "1:0",
        Fecha: new Date("2021-03-1"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 79,
        Jornada: "15",
        Equipo1: "Team Queso",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-03-1"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 80,
        Jornada: "16",
        Equipo1: "eMonkeyz Club",
        Equipo2: "Movistar Riders",
        Resultado: "1:0",
        Fecha: new Date("2021-03-4"),
        Ganador: "eMonkeyz Club",
    },
    {   
        _id: 81,
        Jornada: "16",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "S2V Esports",
        Resultado: "1:0",
        Fecha: new Date("2021-03-4"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 82,
        Jornada: "16",
        Equipo1: "BCN Squad",
        Equipo2: "Team Queso",
        Resultado: "0:1",
        Fecha: new Date("2021-03-4"),
        Ganador: "Team Queso",
    },
    {   
        _id: 83,
        Jornada: "16",
        Equipo1: "Vodafone Giants",
        Equipo2: "UCAM Esports Club",
        Resultado: "1:0",
        Fecha: new Date("2021-03-4"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 84,
        Jornada: "16",
        Equipo1: "G2 Arctic",
        Equipo2: "Cream Real Betis",
        Resultado: "1:0",
        Fecha: new Date("2021-03-4"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 85,
        Jornada: "17",
        Equipo1: "Cream Real Betis",
        Equipo2: "Team Queso",
        Resultado: "1:0",
        Fecha: new Date("2021-03-8"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 86,
        Jornada: "17",
        Equipo1: "eMonkeyz Club",
        Equipo2: "BCN Squad",
        Resultado: "1:0",
        Fecha: new Date("2021-03-8"),
        Ganador: "eMonkeyz Club",
    },
    {   
        _id: 87,
        Jornada: "17",
        Equipo1: "MAD Lions Madrid",
        Equipo2: "G2 Arctic",
        Resultado: "1:0",
        Fecha: new Date("2021-03-8"),
        Ganador: "MAD Lions Madrid",
    },
    {   
        _id: 88,
        Jornada: "17",
        Equipo1: "S2V Esports",
        Equipo2: "Vodafone Giants",
        Resultado: "0:1",
        Fecha: new Date("2021-03-8"),
        Ganador: "Vodafone Giants",
    },
    {   
        _id: 89,
        Jornada: "17",
        Equipo1: "Movistar Riders",
        Equipo2: "Ucam Esports Club",
        Resultado: "0:1",
        Fecha: new Date("2021-03-8"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 90,
        Jornada: "18",
        Equipo1: "S2V Esports",
        Equipo2: "Movistar Riders",
        Resultado: "0:1",
        Fecha: new Date("2021-03-11"),
        Ganador: "Movistar Riders",
    },
    {   
        _id: 91,
        Jornada: "18",
        Equipo1: "UCAM Esports Club",
        Equipo2: "eMonkeyz Club",
        Resultado: "1:0",
        Fecha: new Date("2021-03-11"),
        Ganador: "UCAM Esports Club",
    },
    {   
        _id: 92,
        Jornada: "18",
        Equipo1: "BCN Squad",
        Equipo2: "Cream Real Betis",
        Resultado: "0:1",
        Fecha: new Date("2021-03-11"),
        Ganador: "Cream Real Betis",
    },
    {   
        _id: 93,
        Jornada: "18",
        Equipo1: "BCN Squad",
        Equipo2: "S2V Esports",
        Resultado: "0:1",
        Fecha: new Date("2021-03-11"),
        Ganador: "S2V Esports",
    },
    {   
        _id: 94,
        Jornada: "18",
        Equipo1: "Team Queso",
        Equipo2: "MAD Lions Madrid",
        Resultado: "1:0",
        Fecha: new Date("2021-03-11"),
        Ganador: "Team Queso",
    },
    {   
        _id: 95,
        Jornada: "18",
        Equipo1: "Vodafone Giants",
        Equipo2: "G2 Arctic",
        Resultado: "0:1",
        Fecha: new Date("2021-03-11"),
        Ganador: "G2 Arctic",
    },
    {   
        _id: 96,
        Jornada: "18",
        Equipo1: "Cream Real Betis",
        Equipo2: "UCAM Esports Club",
        Resultado: "0:1",
        Fecha: new Date("2021-03-11"),
        Ganador: "UCAM Esports Club",
    },
])*/